### PR TITLE
Removed middle name constraint

### PR DESCRIPTION
**Pull request by rarothedude**

### CODE REVIEW

**Comment by Deyter** [comment]
@rarothedude 
Sorry, but we won't merge it because we want to not change current behavior.
Please check #12 and the [latest release](https://github.com/ADCI/full-name-parser/releases/latest).
We've added option to disable middle name warning.

**Comment by rarothedude** [comment]
> @rarothedude
> Sorry, but we won't merge it because we want to not change current behavior.
> Please check #12 and the [latest release](https://github.com/ADCI/full-name-parser/releases/latest).
> We've added option to disable middle name warning.

Thanx for adding the option Deyter. Small comment: You copy paste "Last name" in the wiki:

`mandatory_middle_name(bool|integer, optional): Throw error if last name not found.`

**Comment by Deyter** [comment]
Thank you. It will be fixed nearest time.

**Comment by Deyter** [comment]
@rarothedude
Fixed. Thank you for your contribution.

**Pull request closed without merging**
